### ISSUE TITLE
Reads to be renamed

### ISSUE THREAD

**Issue by gs12m** [b-brankovics/grabb#1]
Dear Balázs,
 
I am interesting in building the mtDNA of a parasitic nematode species. It seems the software you’ve built is particularly well suited for that and I have tried to use it.
However I have an error message thrown at me : “entries in the read file must be renamed”. I cannot really understand why and cannot find out an appropriate format. Sampled read 1 looks like: @HS23_6953:2:1305:1339:52188/1
 
Do you have any hints?
Cheers,
G

**Comment by b-brankovics** [comment]
Dear G,

Thank you for reporting this error.

If you run into this problem that means that you are using two read files for the run. When GRAbB gets two read files, then it assumes that they are paired. The way GRAbB handles read pairs is by read id names. I built in a test, so GRAbB checks whether it can find the proper pairs.

So in your example, the read id is `@HS23_6953:2:1305:1339:52188/1` for the forward read, which means the reverse is probably `@HS23_6953:2:1305:1339:52188/2`. The problem is that it will look for the whole `@HS23_6953:2:1305:1339:52188/1` string inside the reverse file and fail. The problem is that there is no space between `@HS23_6953:2:1305:1339:52188` and `/1`.

There is a helper program, `rename_fastq`, which can rename the read files for you. Using the renamed read files should solve the problem.

Thanks for using GRAbB!
Cheers,
Balázs
